const features = [
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
    title: 'AI-Generated Questions',
    desc: 'Every assessment is freshly generated by Gemini AI — no question banks, no repetition. Get challenged with real-world scenarios every time.',
    color: 'blue',
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414A1 1 0 0120 9.414V19a2 2 0 01-2 2z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
    title: 'Detailed Evaluation Report',
    desc: 'Receive a full Markdown report analyzing every wrong answer — with explanations, root-cause analysis, and a custom study roadmap.',
    color: 'indigo',
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path d="M13 10V3L4 14h7v7l9-11h-7z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
    title: 'Progressive Difficulty',
    desc: 'Seven domain sections, each with five questions scaling from Easy to Expert. Built to expose real knowledge gaps, not just test surface memory.',
    color: 'violet',
  },
]

const colorMap = {
  blue: { bg: 'bg-blue-50', icon: 'text-blue-600', accent: 'bg-blue-600' },
  indigo: { bg: 'bg-indigo-50', icon: 'text-indigo-600', accent: 'bg-indigo-600' },
  violet: { bg: 'bg-violet-50', icon: 'text-violet-600', accent: 'bg-violet-600' },
}

export default function FeaturesSection() {
  return (
    <section id="features" className="bg-gray-950 py-24 px-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-16 space-y-3">
          <span className="inline-block bg-blue-900/40 text-blue-400 text-xs font-semibold px-3 py-1.5 rounded-full border border-blue-800/50">
            Why Choose Us
          </span>
          <h2 className="text-4xl font-extrabold text-white">
            Built for Serious Career Growth
          </h2>
          <p className="text-gray-400 max-w-xl mx-auto text-base leading-relaxed">
            No fluff. Pure signal. Every feature is designed to give you an honest picture of where you stand and exactly what to do next.
          </p>
        </div>

        {/* Feature cards */}
        <div className="grid md:grid-cols-3 gap-6">
          {features.map((feat) => {
            const c = colorMap[feat.color]
            return (
              <div
                key={feat.title}
                className="group bg-gray-900 border border-gray-800 rounded-2xl p-7 hover:border-gray-700 transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl cursor-default"
              >
                <div className={`inline-flex items-center justify-center w-12 h-12 rounded-xl ${c.bg} ${c.icon} mb-5 transition-transform duration-300 group-hover:scale-110`}>
                  {feat.icon}
                </div>
                <h3 className="text-lg font-bold text-white mb-2.5">{feat.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{feat.desc}</p>
              </div>
            )
          })}
        </div>

        {/* Process steps */}
        <div className="mt-20">
          <h3 className="text-center text-2xl font-bold text-white mb-12">How It Works</h3>
          <div className="grid md:grid-cols-3 gap-8 relative">
            {/* Connector line */}
            <div className="hidden md:block absolute top-6 left-1/3 right-1/3 h-0.5 bg-gradient-to-r from-blue-800 to-blue-800 via-blue-600" />

            {[
              { step: '01', title: 'Start Assessment', desc: 'Click the button and immediately receive a freshly generated 35-question Data Science Expert quiz.' },
              { step: '02', title: 'Submit Answers', desc: 'Work through all seven domains at your own pace, then submit your final selections.' },
              { step: '03', title: 'Get Your Report', desc: 'Receive a detailed AI-written Markdown report pinpointing your strengths, gaps, and a custom study plan.' },
            ].map(item => (
              <div key={item.step} className="text-center space-y-3">
                <div className="w-12 h-12 rounded-full bg-blue-600 text-white font-bold text-sm flex items-center justify-center mx-auto shadow-lg shadow-blue-900/50 relative z-10">
                  {item.step}
                </div>
                <h4 className="text-white font-semibold text-base">{item.title}</h4>
                <p className="text-gray-500 text-sm leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
