import os
import re
import time
import pathlib
from datetime import datetime, timezone
from dotenv import load_dotenv
from google import genai
from google.genai import types
from fpdf import FPDF

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
MODEL_ID = os.getenv("GEMINI_MODEL", "gemini-3.5-flash")

# ─── Paths ────────────────────────────────────────────────────────────────────
_AGENT_DIR  = pathlib.Path(__file__).resolve().parent          # backend/app/agents/
_BACKEND_DIR = _AGENT_DIR.parent.parent                        # backend/
_REPORTS_DIR = _BACKEND_DIR / "generated_reports"


def generate_evaluation_report(score: int, total_questions: int, wrong_answers: list[dict]) -> str | None:
    """
    Generates a detailed, encouraging evaluation report in Markdown format
    using the Gemini API, given the user's score and wrong answers.
    """
    # Format the wrong answers into a readable block for the LLM prompt
    wrong_answers_formatted = ""
    for i, wa in enumerate(wrong_answers, 1):
        section_info = f" [Section: {wa.get('section_name')}]" if wa.get('section_name') else ""
        wrong_answers_formatted += f"""
Question {i}{section_info}:
- Text: {wa.get('question_text')}
- User's Choice: {wa.get('user_answer')}
- Correct Choice: {wa.get('correct_answer')}
- Explanation: {wa.get('explanation', 'N/A')}
"""

    success_rate = (score / total_questions) * 100 if total_questions > 0 else 0

    prompt = f"""
    You are an expert Data Science Career Coach and Technical Mentor. 
    A candidate has just completed a rigorous Data Science Expert technical assessment.
    
    Candidate Assessment Summary:
    - Final Score: {score} / {total_questions} ({success_rate:.1f}% Success Rate)
    
    Details of Incorrect Answers:
    {wrong_answers_formatted}
    
    Please write a highly detailed, professional, and encouraging evaluation report in Markdown format.
    
    Ensure the Markdown report follows this structure:
    1. **Executive Summary**: A high-level overview of the candidate's performance, acknowledging their score in an encouraging, constructive, and professional tone.
    2. **Strengths Analysis**: Highlight the areas they did well in (acknowledging they answered {score} out of {total_questions} correctly) and detail the capabilities they demonstrated.
    3. **Key Growth Areas**: Identify common themes or topics among their incorrect answers (e.g., SQL joins, Pandas grouping, applied statistics) and explain the conceptual gaps.
    4. **Constructive Review of Mistakes**: For each incorrect answer, break down the core concept in a highly educational way. Explain why their chosen option might be a common pitfall, why the correct answer is technically correct, and what rule or framework to apply next time.
    5. **Custom Actionable Study Plan**: Outline a practical step-by-step roadmap to bridge their technical gaps, recommending specific topics to review and strategies to tackle code-based multiple-choice questions.
    """

    models_to_try = [
        ("Gemini 3.5 Flash", "gemini-3.5-flash"),
        ("Gemini 2.5 Flash", "gemini-2.5-flash"),
        ("Gemini 2.5 Flash Lite", "gemini-2.5-flash-lite")
    ]
    max_retries = 3

    print("\nGenerating AI evaluation report...")

    for i, (display_name, model_id) in enumerate(models_to_try):
        print(f"Trying {display_name}...")
        for attempt in range(max_retries):
            try:
                response = client.models.generate_content(
                    model=model_id,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.6
                    ),
                )
                print("✓ Success")
                print(f"Report generated by {display_name}")
                return response.text
            except Exception as e:
                error_msg = str(e).lower()
                is_transient = any(term in error_msg for term in ["503", "429", "quota", "unavailable", "timeout", "rate limit", "overloaded"])
                
                if attempt < max_retries - 1 and is_transient:
                    sleep_time = 2 ** attempt
                    time.sleep(sleep_time)
                else:
                    status_str = "Error"
                    status_match = re.search(r'(\d{3})', str(e))
                    if status_match:
                        status_str = status_match.group(1)
                    else:
                        if "quota" in error_msg: status_str = "Quota Exceeded"
                        elif "timeout" in error_msg: status_str = "Timeout"

                    print(f"{display_name} unavailable ({status_str})")
                    if i < len(models_to_try) - 1:
                        print(f"Switching to {models_to_try[i+1][0]}...\n")
                    break

    print("Error generating evaluation report in report_writer: All models failed.")
    return None


# ─── PDF helpers ───────────────────────────────────────────────────────────────

class _ReportPDF(FPDF):
    """Custom FPDF2 subclass with header/footer and Markdown-aware rendering."""

    MARGIN      = 18   # mm
    LINE_HEIGHT = 6    # mm baseline line height

    # Colour palette
    _CLR_DARK_BG  = (15,  23,  42)   # slate-950 (cover page bg)
    _CLR_WHITE    = (255, 255, 255)
    _CLR_ACCENT   = (59,  130, 246)  # blue-500
    _CLR_BODY     = (30,  41,  59)   # slate-800 (content pages bg)
    _CLR_HEADING  = (15,  23,  42)   # near-black heading text on white pages
    _CLR_PARA     = (51,  65,  85)   # slate-600 body text
    _CLR_FOOTER   = (148, 163, 184)  # slate-400 footer text

    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(self.MARGIN, self.MARGIN, self.MARGIN)
        # fpdf2 ships with Helvetica (no embed needed)
        self._in_cover = False

    # ── Unicode → ASCII compatibility layer ───────────────────────────────
    @staticmethod
    def _s(text: str) -> str:
        """
        Normalise characters Helvetica cannot encode so FPDF never receives
        a codepoint outside Latin-1.  Applied immediately before every
        write / cell / multi_cell call — never modifies the source content.
        """
        _MAP = [
            ("\u2014", "-"),    # em dash      —
            ("\u2013", "-"),    # en dash      –
            ("\u2022", "*"),    # bullet       •
            ("\u2026", "..."),  # ellipsis     …
            ("\u201c", '"'),    # left dquote  \u201c
            ("\u201d", '"'),    # right dquote \u201d
            ("\u2018", "'"),    # left squote  \u2018
            ("\u2019", "'"),    # right squote \u2019
            ("\u2713", "OK"),   # check mark   \u2713
            ("\u2264", "<="),   # less-or-eq   \u2264
            ("\u2265", ">="),   # greater-eq   \u2265
            ("\u2192", "->"),   # rightarrow   \u2192
            ("\u00b0", "deg"),  # degree sign  \u00b0
            ("\u03b1", "alpha"),("\u03b2", "beta"),("\u03bc", "mu"),
            ("\u03c3", "sigma"),("\u03bb", "lambda"),("\u03b5", "epsilon"),
        ]
        for uni, asc in _MAP:
            text = text.replace(uni, asc)
        # Final safety net: drop any remaining non-Latin-1 codepoints
        return text.encode("latin-1", errors="replace").decode("latin-1")

    # ── Footer (every content page) ──────────────────────────────────────────
    def footer(self):
        if self._in_cover:
            return
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self._CLR_FOOTER)
        self.cell(
            0, 6,
            self._s("Generated by PrepVector Cognitive Career Assessment System"),
            align="C",
        )

    # ── Cover page builder ────────────────────────────────────────────────────
    def cover_page(
        self,
        candidate_name: str,
        assessment_date: str,
        generated_on: str,
        weighted_score: int,
        total_correct: int,
        total_questions: int,
    ) -> None:
        self._in_cover = True
        self.add_page()
        page_w = self.w
        page_h = self.h

        # Full-bleed dark background
        self.set_fill_color(*self._CLR_DARK_BG)
        self.rect(0, 0, page_w, page_h, style="F")

        # Blue accent bar at top
        self.set_fill_color(*self._CLR_ACCENT)
        self.rect(0, 0, page_w, 4, style="F")

        # ── Logo / system name ──
        self.set_y(36)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self._CLR_ACCENT)
        self.cell(0, 8, self._s("PREPVECTOR"), align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self._CLR_FOOTER)
        self.cell(0, 5, self._s("Cognitive Career Assessment System"), align="C", new_x="LMARGIN", new_y="NEXT")

        # ── Main title ──
        self.ln(14)
        self.set_font("Helvetica", "B", 30)
        self.set_text_color(*self._CLR_WHITE)
        self.multi_cell(0, 13, self._s("AI Evaluation\nReport"), align="C")

        # ── Thin separator ──
        self.ln(10)
        self.set_draw_color(*self._CLR_ACCENT)
        self.set_line_width(0.5)
        x_margin = 40
        self.line(x_margin, self.get_y(), page_w - x_margin, self.get_y())

        # ── Candidate block ──
        self.ln(12)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self._CLR_FOOTER)
        self.cell(0, 6, self._s("CANDIDATE"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*self._CLR_WHITE)
        self.cell(0, 10, self._s(candidate_name), align="C", new_x="LMARGIN", new_y="NEXT")

        # ── Dates ──
        self.ln(8)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self._CLR_FOOTER)
        self.cell(0, 5, self._s(f"Assessment Date: {assessment_date}"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, self._s(f"Report Generated: {generated_on}"), align="C", new_x="LMARGIN", new_y="NEXT")

        # ── Score cards ──
        self.ln(18)
        card_w  = 64
        card_h  = 34
        gap     = 8
        total_w = card_w * 2 + gap
        start_x = (page_w - total_w) / 2

        cards = [
            ("FINAL SCORE",    f"{weighted_score} / 70",  "weighted points"),
            ("CORRECT ANSWERS", f"{total_correct} / {total_questions}", "questions"),
        ]
        for ci, (label, value, sub) in enumerate(cards):
            cx = start_x + ci * (card_w + gap)
            cy = self.get_y()
            # Card background
            self.set_fill_color(30, 41, 59)  # slate-800
            self.rect(cx, cy, card_w, card_h, style="F")
            # Label
            self.set_xy(cx, cy + 5)
            self.set_font("Helvetica", "B", 7)
            self.set_text_color(*self._CLR_FOOTER)
            self.cell(card_w, 4, self._s(label), align="C", new_x="LMARGIN", new_y="NEXT")
            # Value
            self.set_x(cx)
            self.set_font("Helvetica", "B", 18)
            self.set_text_color(*self._CLR_WHITE)
            self.cell(card_w, 10, self._s(value), align="C", new_x="LMARGIN", new_y="NEXT")
            # Sub-label
            self.set_x(cx)
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*self._CLR_FOOTER)
            self.cell(card_w, 4, self._s(sub), align="C")

        self._in_cover = False

    # ── Lightweight Markdown renderer ─────────────────────────────────────────
    def render_markdown(self, markdown_text: str) -> None:
        """
        Render a subset of Markdown onto the current page(s):
          - # H1  -> large bold heading with blue rule
          - ## H2 -> medium bold heading
          - **bold** inline fragments
          - - bullet / * bullet
          - blank line -> paragraph break
          - everything else -> body paragraph
        """
        usable_w = self.w - 2 * self.MARGIN

        def _write_mixed(text: str, font_size: int = 10) -> None:
            """Write a single line that may contain **bold** fragments."""
            parts = re.split(r"(\*\*[^*]+\*\*)", text)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    self.set_font("Helvetica", "B", font_size)
                    self.write(self.LINE_HEIGHT, self._s(part[2:-2]))
                else:
                    self.set_font("Helvetica", "", font_size)
                    self.write(self.LINE_HEIGHT, self._s(part))

        for raw_line in markdown_text.splitlines():
            line = raw_line.rstrip()

            # ── H1 heading ──────────────────────────────────────────────────
            if line.startswith("# "):
                text = self._s(line[2:].strip())
                self.ln(4)
                self.set_font("Helvetica", "B", 16)
                self.set_text_color(*self._CLR_HEADING)
                self.multi_cell(usable_w, 8, text, new_x="LMARGIN", new_y="NEXT")
                # Accent underline
                self.set_draw_color(*self._CLR_ACCENT)
                self.set_line_width(0.6)
                self.line(
                    self.MARGIN, self.get_y(),
                    self.MARGIN + usable_w, self.get_y()
                )
                self.ln(3)

            # ── H2 heading ──────────────────────────────────────────────────
            elif line.startswith("## "):
                text = self._s(line[3:].strip())
                self.ln(3)
                self.set_font("Helvetica", "B", 13)
                self.set_text_color(*self._CLR_HEADING)
                self.multi_cell(usable_w, 7, text, new_x="LMARGIN", new_y="NEXT")
                self.ln(1)

            # ── H3 heading ──────────────────────────────────────────────────
            elif line.startswith("### "):
                text = self._s(line[4:].strip())
                self.ln(2)
                self.set_font("Helvetica", "B", 11)
                self.set_text_color(*self._CLR_HEADING)
                self.multi_cell(usable_w, 6, text, new_x="LMARGIN", new_y="NEXT")

            # ── Bullet point ─────────────────────────────────────────────────
            elif re.match(r"^[-*+]\s+", line):
                text = re.sub(r"^[-*+]\s+", "", line).strip()
                self.set_text_color(*self._CLR_PARA)
                self.set_x(self.MARGIN + 3)
                self.set_font("Helvetica", "", 9)
                self.write(self.LINE_HEIGHT, "*  ")  # ASCII bullet
                _write_mixed(text, font_size=9)
                self.ln(self.LINE_HEIGHT)

            # ── Blank line / paragraph separator ─────────────────────────────
            elif line.strip() == "":
                self.ln(3)

            # ── Normal paragraph text ────────────────────────────────────────
            else:
                self.set_text_color(*self._CLR_PARA)
                self.set_x(self.MARGIN)
                _write_mixed(line.strip(), font_size=9)
                self.ln(self.LINE_HEIGHT)


# ─── Public API ────────────────────────────────────────────────────────────────────

def generate_pdf_report(
    markdown_text: str,
    candidate_name: str = "Candidate",
    assessment_date: str = "",
    weighted_score: int = 0,
    total_correct: int = 0,
    total_questions: int = 35,
) -> str:
    """
    Converts the Markdown evaluation report into a polished multi-page PDF.

    Returns the absolute path of the saved PDF file.
    """
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    now        = datetime.now(timezone.utc)
    timestamp  = now.strftime("%Y%m%d_%H%M%S")
    generated_on = now.strftime("%B %d, %Y at %H:%M UTC")
    if not assessment_date:
        assessment_date = now.strftime("%B %d, %Y")

    pdf = _ReportPDF()

    # ── Page 1: Cover ──
    pdf.cover_page(
        candidate_name  = candidate_name or "Candidate",
        assessment_date = assessment_date,
        generated_on    = generated_on,
        weighted_score  = weighted_score,
        total_correct   = total_correct,
        total_questions = total_questions,
    )

    # ── Following pages: Markdown body ──
    pdf.add_page()
    # White page background
    pdf.set_fill_color(255, 255, 255)
    pdf.rect(0, 0, pdf.w, pdf.h, style="F")
    pdf.render_markdown(markdown_text)

    # ── Save ──
    filename = f"assessment_report_{timestamp}.pdf"
    out_path = _REPORTS_DIR / filename
    pdf.output(str(out_path))

    print(f"[report_writer] ✅  PDF saved → {out_path}")
    return str(out_path.resolve())
